/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author danie
 */
public class ControlEstablecimientos extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    public ControlEstablecimientos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuper = new javax.swing.JPanel();
        codigoTf = new javax.swing.JTextField();
        ubicacionTf = new javax.swing.JTextField();
        direccionTf = new javax.swing.JTextField();
        directorTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        separadorDerecha = new javax.swing.JSeparator();
        separadorIzquierda = new javax.swing.JSeparator();
        panelBtns = new javax.swing.JPanel();
        guardarBtn = new javax.swing.JButton();
        consultarBtn = new javax.swing.JButton();
        actualizarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSuper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codigoTf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelSuper.add(codigoTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 100, 30));

        ubicacionTf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelSuper.add(ubicacionTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 210, 30));

        direccionTf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelSuper.add(direccionTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 430, 30));

        directorTf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelSuper.add(directorTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 430, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("DIRECTOR(A):");
        panelSuper.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("UBICACION:");
        panelSuper.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 90, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("CODIGO:");
        panelSuper.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CONTROL ESTABLECIMIENTOS");
        panelSuper.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 600, 70));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("DIRECCION:");
        panelSuper.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 30));
        panelSuper.add(separadorDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 400));
        panelSuper.add(separadorIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 400));

        guardarBtn.setBackground(new java.awt.Color(197, 197, 197));
        guardarBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        guardarBtn.setForeground(new java.awt.Color(0, 0, 0));
        guardarBtn.setText("GUARDAR");
        guardarBtn.setFocusPainted(false);
        panelBtns.add(guardarBtn);

        consultarBtn.setBackground(new java.awt.Color(197, 197, 197));
        consultarBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        consultarBtn.setForeground(new java.awt.Color(0, 0, 0));
        consultarBtn.setText("CONSULTAR");
        consultarBtn.setFocusPainted(false);
        panelBtns.add(consultarBtn);

        actualizarBtn.setBackground(new java.awt.Color(197, 197, 197));
        actualizarBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        actualizarBtn.setForeground(new java.awt.Color(0, 0, 0));
        actualizarBtn.setText("ACTUALIZAR");
        actualizarBtn.setFocusPainted(false);
        panelBtns.add(actualizarBtn);

        eliminarBtn.setBackground(new java.awt.Color(197, 197, 197));
        eliminarBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        eliminarBtn.setForeground(new java.awt.Color(0, 0, 0));
        eliminarBtn.setText("ELIMINAR");
        eliminarBtn.setFocusPainted(false);
        panelBtns.add(eliminarBtn);

        panelSuper.add(panelBtns, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 540, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuper, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlEstablecimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlEstablecimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlEstablecimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlEstablecimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlEstablecimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actualizarBtn;
    public javax.swing.JTextField codigoTf;
    public javax.swing.JButton consultarBtn;
    public javax.swing.JTextField direccionTf;
    public javax.swing.JTextField directorTf;
    public javax.swing.JButton eliminarBtn;
    public javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelBtns;
    private javax.swing.JPanel panelSuper;
    private javax.swing.JSeparator separadorDerecha;
    private javax.swing.JSeparator separadorIzquierda;
    public javax.swing.JTextField ubicacionTf;
    // End of variables declaration//GEN-END:variables
}
