/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author danie
 */
public class Especialidades extends javax.swing.JFrame {

    /**
     * Creates new form ControlEspecialidades
     */
    public Especialidades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuper = new javax.swing.JPanel();
        volverBtn = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelBtns = new javax.swing.JPanel();
        nuevoBtn = new javax.swing.JButton();
        obtenerDatosBtn = new javax.swing.JButton();
        actualizarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        coordinadorInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codigoInput = new javax.swing.JTextField();
        nombreInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        especialidadesTbl = new javax.swing.JTable();
        seccionBusqueda = new javax.swing.JPanel();
        buscarBtn = new javax.swing.JButton();
        busquedaInput = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        asignarCoordinadorBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelSuper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverBtn.setBackground(new java.awt.Color(102, 102, 102));
        volverBtn.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("volver");
        volverBtn.setFocusPainted(false);
        panelSuper.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CONTROL ESPECIALIDADES");
        panelSuper.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 600, 70));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("*CODIGO:");
        panelSuper.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 80, 30));

        nuevoBtn.setBackground(new java.awt.Color(197, 197, 197));
        nuevoBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nuevoBtn.setForeground(new java.awt.Color(0, 0, 0));
        nuevoBtn.setText("NUEVO");
        nuevoBtn.setFocusPainted(false);
        panelBtns.add(nuevoBtn);

        obtenerDatosBtn.setBackground(new java.awt.Color(197, 197, 197));
        obtenerDatosBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        obtenerDatosBtn.setForeground(new java.awt.Color(0, 0, 0));
        obtenerDatosBtn.setText("OBTENER DATOS");
        obtenerDatosBtn.setFocusPainted(false);
        panelBtns.add(obtenerDatosBtn);

        actualizarBtn.setBackground(new java.awt.Color(197, 197, 197));
        actualizarBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        actualizarBtn.setForeground(new java.awt.Color(0, 0, 0));
        actualizarBtn.setText("ACTUALIZAR");
        actualizarBtn.setFocusPainted(false);
        panelBtns.add(actualizarBtn);

        eliminarBtn.setBackground(new java.awt.Color(197, 197, 197));
        eliminarBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        eliminarBtn.setForeground(new java.awt.Color(0, 0, 0));
        eliminarBtn.setText("ELIMINAR");
        eliminarBtn.setFocusPainted(false);
        panelBtns.add(eliminarBtn);

        panelSuper.add(panelBtns, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 540, 40));

        coordinadorInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelSuper.add(coordinadorInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 280, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("*NOMBRE:");
        panelSuper.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 80, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("COORDINADOR:");
        panelSuper.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 120, 30));

        codigoInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelSuper.add(codigoInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 100, 30));

        nombreInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelSuper.add(nombreInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 410, 30));

        especialidadesTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "ALUMNOS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        especialidadesTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(especialidadesTbl);
        if (especialidadesTbl.getColumnModel().getColumnCount() > 0) {
            especialidadesTbl.getColumnModel().getColumn(0).setResizable(false);
            especialidadesTbl.getColumnModel().getColumn(2).setResizable(false);
        }

        panelSuper.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 540, 220));

        seccionBusqueda.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        buscarBtn.setBackground(new java.awt.Color(197, 197, 197));
        buscarBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buscarBtn.setForeground(new java.awt.Color(0, 0, 0));
        buscarBtn.setText("BUSCAR");
        buscarBtn.setFocusPainted(false);
        seccionBusqueda.add(buscarBtn);

        busquedaInput.setPreferredSize(new java.awt.Dimension(150, 30));
        seccionBusqueda.add(busquedaInput);

        panelSuper.add(seccionBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 540, 40));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        asignarCoordinadorBtn.setBackground(new java.awt.Color(197, 197, 197));
        asignarCoordinadorBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        asignarCoordinadorBtn.setForeground(new java.awt.Color(0, 0, 0));
        asignarCoordinadorBtn.setText("ASIGNAR");
        asignarCoordinadorBtn.setFocusPainted(false);
        asignarCoordinadorBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(asignarCoordinadorBtn);

        panelSuper.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuper, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Especialidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Especialidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Especialidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Especialidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Especialidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actualizarBtn;
    public javax.swing.JButton asignarCoordinadorBtn;
    public javax.swing.JButton buscarBtn;
    public javax.swing.JTextField busquedaInput;
    public javax.swing.JTextField codigoInput;
    public javax.swing.JTextField coordinadorInput;
    public javax.swing.JButton eliminarBtn;
    public javax.swing.JTable especialidadesTbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nombreInput;
    public javax.swing.JButton nuevoBtn;
    public javax.swing.JButton obtenerDatosBtn;
    private javax.swing.JPanel panelBtns;
    private javax.swing.JPanel panelSuper;
    private javax.swing.JPanel seccionBusqueda;
    public javax.swing.JToggleButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
