/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author danie
 */
public class Establecimientos extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    int xMouse, yMouse;
    public Establecimientos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuper = new javax.swing.JPanel();
        codigoInput = new javax.swing.JTextField();
        ubicacionInput = new javax.swing.JTextField();
        nombreInput = new javax.swing.JTextField();
        direccionInput = new javax.swing.JTextField();
        directorInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        separadorDerecha = new javax.swing.JSeparator();
        separadorIzquierda = new javax.swing.JSeparator();
        panelBtns = new javax.swing.JPanel();
        nuevoBtn = new javax.swing.JButton();
        obtenerBtn = new javax.swing.JButton();
        actualizarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JToggleButton();
        paneForLocation = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        establecimientosTbl = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cargarListaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        panelSuper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codigoInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelSuper.add(codigoInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 100, 30));

        ubicacionInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelSuper.add(ubicacionInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 430, 30));

        nombreInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelSuper.add(nombreInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 230, 30));

        direccionInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelSuper.add(direccionInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 430, 30));

        directorInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelSuper.add(directorInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 430, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("DIRECTOR(A):");
        panelSuper.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("*NOMBRE:");
        panelSuper.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 90, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("*UBICACION:");
        panelSuper.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("*DIRECCION:");
        panelSuper.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CONTROL ESTABLECIMIENTOS");
        panelSuper.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, 40));
        panelSuper.add(separadorDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 300));
        panelSuper.add(separadorIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 300));

        nuevoBtn.setBackground(new java.awt.Color(197, 197, 197));
        nuevoBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nuevoBtn.setForeground(new java.awt.Color(0, 0, 0));
        nuevoBtn.setText("NUEVO");
        nuevoBtn.setFocusPainted(false);
        panelBtns.add(nuevoBtn);

        obtenerBtn.setBackground(new java.awt.Color(197, 197, 197));
        obtenerBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        obtenerBtn.setForeground(new java.awt.Color(0, 0, 0));
        obtenerBtn.setText("OBTENER DATOS");
        obtenerBtn.setFocusPainted(false);
        panelBtns.add(obtenerBtn);

        actualizarBtn.setBackground(new java.awt.Color(197, 197, 197));
        actualizarBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        actualizarBtn.setForeground(new java.awt.Color(0, 0, 0));
        actualizarBtn.setText("ACTUALIZAR");
        actualizarBtn.setFocusPainted(false);
        panelBtns.add(actualizarBtn);

        eliminarBtn.setBackground(new java.awt.Color(197, 197, 197));
        eliminarBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        eliminarBtn.setForeground(new java.awt.Color(0, 0, 0));
        eliminarBtn.setText("ELIMINAR");
        eliminarBtn.setFocusPainted(false);
        panelBtns.add(eliminarBtn);

        panelSuper.add(panelBtns, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 540, 40));

        volverBtn.setBackground(new java.awt.Color(102, 102, 102));
        volverBtn.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("volver");
        volverBtn.setFocusPainted(false);
        panelSuper.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        paneForLocation.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                paneForLocationMouseDragged(evt);
            }
        });
        paneForLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneForLocationMousePressed(evt);
            }
        });

        javax.swing.GroupLayout paneForLocationLayout = new javax.swing.GroupLayout(paneForLocation);
        paneForLocation.setLayout(paneForLocationLayout);
        paneForLocationLayout.setHorizontalGroup(
            paneForLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        paneForLocationLayout.setVerticalGroup(
            paneForLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelSuper.add(paneForLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 20));

        establecimientosTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "UBICACION", "TOTAL ALUMNOS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        establecimientosTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(establecimientosTbl);
        if (establecimientosTbl.getColumnModel().getColumnCount() > 0) {
            establecimientosTbl.getColumnModel().getColumn(0).setResizable(false);
        }

        panelSuper.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 540, 290));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("*CODIGO:");
        panelSuper.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, 30));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        cargarListaBtn.setBackground(new java.awt.Color(197, 197, 197));
        cargarListaBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cargarListaBtn.setForeground(new java.awt.Color(0, 0, 0));
        cargarListaBtn.setText("CARGAR LISTA");
        cargarListaBtn.setFocusPainted(false);
        jPanel1.add(cargarListaBtn);

        panelSuper.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuper, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paneForLocationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneForLocationMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_paneForLocationMousePressed

    private void paneForLocationMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneForLocationMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_paneForLocationMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Establecimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Establecimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Establecimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Establecimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Establecimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actualizarBtn;
    public javax.swing.JButton cargarListaBtn;
    public javax.swing.JTextField codigoInput;
    public javax.swing.JTextField direccionInput;
    public javax.swing.JTextField directorInput;
    public javax.swing.JButton eliminarBtn;
    public javax.swing.JTable establecimientosTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nombreInput;
    public javax.swing.JButton nuevoBtn;
    public javax.swing.JButton obtenerBtn;
    public javax.swing.JPanel paneForLocation;
    private javax.swing.JPanel panelBtns;
    private javax.swing.JPanel panelSuper;
    private javax.swing.JSeparator separadorDerecha;
    private javax.swing.JSeparator separadorIzquierda;
    public javax.swing.JTextField ubicacionInput;
    public javax.swing.JToggleButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
